### ISSUE TITLE
Images is really large, and slow to load

### ISSUE THREAD

**Issue by DCjanus** [Hoverbear/hoverbear.org#14]
Hi, Thanks for your posts, which is really nice. I'm working for a Chinese company to optimize their network traffic cost in image, so I noticed that banner in each post is really large.

Like this pic: <https://hoverbear.org/processed_images/c1bc11c7b5eb070f00.png>

It cost `11MB` in network, and if convert it to WebP with [imagemagick](https://imagemagick.org/index.php), it would be `118KB`, in AVIF, it's only `38K`.

How about quality？In my official job, we compare images with [PSNR](https://en.wikipedia.org/wiki/Peak_signal-to-noise_ratio):

|action|size|PSNR|
|---|---|---|
|PNG -> WebP | 11MB -> 118KB | 42.7807|
|PNG -> AVIF| 11MB -> 38KB | 42.1162|

> PS: usually, we believe that human would not be able to detect difference if PSNR great than 40.

refs:
+ [Can I Use WebP or AVIF ?](https://caniuse.com/?search=webp%20or%20avif)
+ [Github App To Optimizes Your Image](https://github.com/marketplace/imgbot/plan/MLP_kgDNGw8)

![图片](https://user-images.githubusercontent.com/15802727/154645370-42d51f5e-0325-4ceb-af77-52a84f9c2a8f.png)

**Comment by Hoverbear** [comment]
Thanks for highlighting this! I have [responsive images set up](https://github.com/Hoverbear/hoverbear.org/blob/590954a925377802730192f385cc4a79315a8b0d/templates/macros/image.html#L5-L19) but you're right, I could probably do some optimizing.

**Comment by Hoverbear** [comment]
I did an image optimization pass using a script I committed in https://github.com/Hoverbear/hoverbear.org/commit/79c28d5a3d6f1bfddd7af01630d53938cf4858e7
