### ISSUE TITLE
RSS Feed links are wrong

### ISSUE THREAD

**Issue by porglezomp** [Hoverbear/hoverbear.org#6]
For example, the link that should go to https://hoverbear.org/2016/09/29/an-https-terminator-box/ instead points to https://hoverbear.org/hoverbear.org/2016/09/29/an-https-terminator-box/, which is a 404.

**Comment by porglezomp** [comment]
I've investigated a bit, and your root `<link>` tag in `feed.xml` is ending up as `<link>https://hoverbear.org/hoverbear.org/</link>`.

It looks like for some reason `{{ site.url }}{{ site.baseurl }}` is rendering as the duplicated one even though `_config.yml` lists `baseurl` as the empty string.

**Comment by Hoverbear** [comment]
Ack! Yes, this is because Github Pages sets `site.baseurl` to something different than my `.config.yml`. Thanks for spotting this!
